jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '22'
     - run: npm install
     - run: chmod +x ./node_modules/.bin/jest  # Ensure Jest has execute permissions
     - run: npm test --verbose  # Run the tests with verbose output